<!DOCTYPE html>
<html lang="is">
<meta charset="utf-8">
<head>
    <link rel="stylesheet" type="text/css" href="Lokaverkefni.css">
    <!-- linkur á stafina sem eg nota -->
    <link href='https://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
    <meta charset="utf-8">
    <title>Lokaverkefni</title>
    <link rel="icon" type="image/ico" href="VSH_Skilaverkefni2_BAJ.png">
</head>
<div class="LOGO">
<img src="VSH_Skilaverkefni2_BAJ.svg">
</div>
<body class="group liturbody2">
    <header class="group">

        <?php require './includes/Menu.php'; ?>
        
        </header>

<div class="group">
        <div class="textiPlayfairborder" id="Verslun1">
            Verslun
        </div>
        <!-- <div class="rammi1-2"> 
        <a href="berjamo.html"><img src="vsh Myndir lokaverkefni/berjamo.png"></a>
        </div>
        <div class="rammi2-2">
            
            <a href="fjörusteinar.HTML"><img src="vsh Myndir lokaverkefni/fjörusteinar.png"></a>
        </div>
        <div class="rammi1-2">
        <a href="göngutur.html"><img src="vsh Myndir lokaverkefni/göngutur.png"></a>
        </div>
        <div class="rammi2-2">
            
            <a href="klaki 1.html"><img src="vsh Myndir lokaverkefni/klaki 1.png"></a>
        </div>
        <div class="rammi1-2">
        <a href="klaki 2.html"><img src="vsh Myndir lokaverkefni/klaki 2.png"></a>
        </div>
        <div class="rammi2-2">
            
            <a href="jarnisblafjoll.html"><img src="vsh Myndir lokaverkefni/jarnisblafjoll.png"></a>
        </div> -->
        <div class="rammi1-2">
        <a href="höfn hfj.php"><img src="vsh Myndir lokaverkefni/höfn hfj.png"></a>
        </div>
        <div class="rammi2-2">
            
            <a href="flugeldar.php"><img src="vsh Myndir lokaverkefni/flugeldar.png"></a>
        </div>
    </div>
    <?php require './includes/SocialMediaButtons.php'; ?>
    <?php require './includes/Contact.php'; ?>